# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WA Project Desafio B CI - Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint-and-test-api:
    runs-on: ubuntu-latest
    name: Check API Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - name: Install packages
      run: yarn install
      working-directory: ./backend
    - name: Run Linter
      run: yarn lint
      working-directory: ./backend
    - name: Run unit-tests
      run: yarn test --passWithNoTests 
      working-directory: ./backend
  lint-and-test-app:
    runs-on: ubuntu-latest
    name: Check APP Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
        cache-dependency-path: './frontend'
        cache: 'yarn'
    - name: Cypress
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
    - name: Install packages
      run: yarn install
      working-directory: ./frontend
    - name: Run Linter
      run: yarn lint
      working-directory: ./frontend
    - name: Run Linter
      run: yarn lint
      working-directory: ./frontend
    - name: Run unit-tests
      run: yarn test --passWithNoTests 
      working-directory: ./frontend
    - name: Run e2e tests
      run: yarn test:e2e
      working-directory: ./frontend      