# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WA Project Desafio B CI - Continuous Integration

on:
  push:
    branches: [ "main" ]
jobs:
  tests-api:
    runs-on: ubuntu-latest
    name: Check API Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./backend
        yarn install
        yarn lint
        yarn test --passWithNoTests 
  tests-app:
    runs-on: ubuntu-latest
    needs: [tests-api]
    name: Check APP Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./frontend
        yarn install
        yarn lint
        yarn test --passWithNoTests
  deploy-api:
    runs-on: ubuntu-latest
    needs: [tests-api, tests-app]
    name: Build and Deploy API
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./backend
        yarn install
        yarn build
    - name: Publish
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        key: ${{ secrets.DH_MASTELARI_SSHKEY }}
        passphrase: ${{ secrets.DH_MASTELARI_SSHPASSPHRASE }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        source: "./dist/*"
        target: "~/wpdesafiob-api.mastelari.ml/"
  deploy-app:
    runs-on: ubuntu-latest
    needs: [deploy-api]
    name: Build and Deploy APP
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./frontend
        yarn install
        yarn build
    - name: Publish
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        key: ${{ secrets.DH_MASTELARI_SSHKEY }}
        passphrase: ${{ secrets.DH_MASTELARI_SSHPASSPHRASE }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        source: "./components/*,./pages/*,./public/*,next.config.js,package.json,tsconfig.json,yarn.lock"
        target: "~/wpdesafiob.mastelari.ml/"
    - name: Post-publishing actions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        key: ${{ secrets.DH_MASTELARI_SSHKEY }}
        passphrase: ${{ secrets.DH_MASTELARI_SSHPASSPHRASE }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        script: |
          cd ~/wpdesafiob.mastelari.ml/
          yarn install
          yarn build
