# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WA Project Desafio B CI - Continuous Integration

on:
  push:
    branches: [ "main" ]
jobs:
  tests-api:
    runs-on: ubuntu-latest
    name: Check API Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./backend
        yarn install
        yarn lint
        yarn test --passWithNoTests 
  tests-app:
    runs-on: ubuntu-latest
    name: Check APP Lint and run Tests
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./frontend
        yarn install
        yarn lint
        yarn test --passWithNoTests
  deploy-api:
    runs-on: ubuntu-latest
    needs: [tests-api, tests-app]
    name: Build and Deploy API
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./backend
        yarn install
        yarn build
        cp package.json ./dist/
    - name: Publish
      uses: ArthurYdalgo/github-action-scp@master
      with:
        local: "backend/dist"
        remote: "wpdesafiob-api.mastelari.ml"
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        password : ${{ secrets.DH_MASTELARI_SSHPASSWORD }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
    - name: Post-publishing actions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        password : ${{ secrets.DH_MASTELARI_SSHPASSWORD }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          cd ~/wpdesafiob-api.mastelari.ml
          yarn install --production
          touch tmp/restart.txt
  deploy-app:
    runs-on: ubuntu-latest
    needs: [deploy-api]
    name: Build and Deploy APP
    steps:
    - uses: actions/checkout@v3
    - name: Bucket actions
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.12'
    - run: |
        cd ./frontend
        yarn install
        yarn build
        tar --exclude={".env.sample",".env.local","README.md","next-env.d.ts","jest.config.ts",".eslintrc.json","__tests__",".next","node_modules",".swc","coverage","out"} -zcvf ../build-content.tar.gz .
    - name: Publish
      uses: ArthurYdalgo/github-action-scp@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        password : ${{ secrets.DH_MASTELARI_SSHPASSWORD }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        local: "build-content.tar.gz"
        remote: "wpdesafiob.mastelari.ml/build-content.tar.gz"
    - name: Post-publishing actions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DH_MASTELARI_SSHHOST }}
        username: ${{ secrets.DH_MASTELARI_SSHUSER }}
        password : ${{ secrets.DH_MASTELARI_SSHPASSWORD }}
        port: ${{ secrets.DH_MASTELARI_SSHPORT }}
        script_stop: true
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          cd ~/wpdesafiob.mastelari.ml
          tar -zxvf build-content.tar.gz
          rm build-content.tar.gz
          yarn install
          yarn build
          touch tmp/restart.txt
